#!/usr/bin/python

import string
import time

flag = 0
with open('./all_flags', 'r') as f:
    data = f.readlines()
    for line in data:
        if len(line) == 33:
            flag += 1

print("all: " + str(flag) + " flags")
